services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: dba
      POSTGRES_DB: dba
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    command: python -m uvicorn dba_agent.web.main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
    environment:
      PYTHONPATH: /app/src
      DB_URL: postgresql://dba:dba@db:5432/dba
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"

volumes:
  pgdata:

  image-worker:
    build: .
    command: python -m dba_agent.workers.image_downloader
    restart: unless-stopped
    environment:
      PYTHONPATH: /app/src
      DB_URL: postgresql://dba:dba@db:5432/dba
    depends_on:
      - db
    volumes:
      - .:/app
