services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: dba
      POSTGRES_PASSWORD: dba
      POSTGRES_DB: dba
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    command: tail -f /dev/null
    environment:
      PYTHONPATH: /app/src
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  pgdata:
